#!/usr/bin/python3
# stotal is will calculate the total CPU-hours, GPU-hours, and TRES-hours for a user or account.

import sys,os,subprocess,shlex
import argparse
import time,datetime
from datetime import date

# Calculate Usage
def calc_usage(inuser, inaccount, instarttime, inendtime):

  # Get job data
  if inuser != None:
    jobdata = subprocess.Popen(['sacct','-anPXD','--units=G','--format=User,Account,Partition,Start,End,AllocTRES','-u',inuser,'-S',instarttime,'-E',inendtime],
    stdout=subprocess.PIPE,
    universal_newlines=True)
  elif inaccount != None:
    jobdata = subprocess.Popen(['sacct','-anPXD','--units=G','--format=User,Account,Partition,Start,End,AllocTRES','-A',inaccount,'-S',instarttime,'-E',inendtime],
    stdout=subprocess.PIPE,
    universal_newlines=True)

  # Converting time to integer time.
  if 'T' not in instarttime:
    instarttime=instarttime+'T00:00:00'
  if 'T' not in inendtime:
    inendtime=inendtime+'T23:59:59'
  pattern = '%Y-%m-%dT%H:%M:%S'
  instart = int(time.mktime(time.strptime(instarttime, pattern)))
  inend = int(time.mktime(time.strptime(inendtime, pattern)))

  # Get Partition TRES Table
  ptresweightcpu={}
  ptresweightmem={}
  ptresweightgpu={}
  partlist = subprocess.Popen(['scontrol','-o','show','partition'], stdout=subprocess.PIPE, universal_newlines=True)
  for line in partlist.stdout:
    #Sanitize input
    line = line.replace("'", "\\'")
    
    #Turn partition information into a hash
    part = dict(s.split("=", 1) for s in shlex.split(line) if '=' in s)
    
    #Get the TRESBillingWeights for a partition
    tresweight = dict(s.split("=", 1) for s in shlex.split(part['TRESBillingWeights'].replace(",", " ")) if '=' in s)
    ptresweightcpu[part["PartitionName"]] = float(tresweight['CPU'])
    ptresweightmem[part["PartitionName"]] = float(tresweight['Mem'].strip('G'))
    if 'Gres/gpu' in tresweight:
      ptresweightgpu[part["PartitionName"]] = float(tresweight['Gres/gpu'])
    else:
      ptresweightgpu[part["PartitionName"]] = 0.0 

  cputot = 0
  gputot = 0
  trestot = 0.

  # Iterate over the jobs
  for job in jobdata.stdout:
    (user,account,partition,start,end,alloctres) = job.strip().split('|')
    
    # Ignore jobs that have no allocation. That means they have never run.
    if alloctres != "":
      # Converting time to integer time.
      if end == "Unknown":
        end = inendtime
      pattern = '%Y-%m-%dT%H:%M:%S'
      start = int(time.mktime(time.strptime(start, pattern)))
      end = int(time.mktime(time.strptime(end, pattern)))
      
      # Check if job actual ran in window.
      if start < inend:
    
        # Parsing AllocTRES.
        atres = dict(s.split("=", 1) for s in shlex.split(alloctres.replace(",", " ")) if '=' in s)
        cpu = int(atres["cpu"])
        mem = float(atres["mem"].strip("G"))
        if 'gres/gpu' in atres:
          gpu = int(atres['gres/gpu'])
        else:
          gpu = 0

        # Sum up the usage
        # Note that this caps the usage only in the window that is specified. The jobs may continue running before and after the window, but we care about the usage in the specific window.
        elapsedwindow = min(end,inend)-max(start,instart)
        print(cpu,gpu,mem,elapsedwindow)
        cputot = cputot+cpu*elapsedwindow
        gputot = gputot+gpu*elapsedwindow
        trestot = trestot+(ptresweightcpu[partition]*float(cpu)+ptresweightmem[partition]*mem+ptresweightgpu[partition]*float(gpu))*float(elapsedwindow)

  # Convert to per hours
  sectohour = 60.0*60.0
  hourrange = (float(inend)-float(instart))/sectohour
  cputot = float(cputot)/sectohour
  gputot = float(gputot)/sectohour
  trestot = float(trestot)/sectohour

  # Print results
  print(f"Number of Hours in Window: {hourrange:.1f} CPU-Hours: {cputot:.1f} GPU-Hours: {gputot:.1f} TRES-Hours: {trestot:.1f}")

# Code starts here.
if __name__ == "__main__":

  desc = (
  """
  stotal
  https://github.com/fasrc/stotal
  ---------------
  stotal is will calculate the total CPU-hours, GPU-hours, and TRES-hours for a Slurm user or account.

  When passed a user or account (note that for accounts outside of what the user is a member of that user must be either an Operator or Administrator), this
  command calculates the total usage for that user or account over the period specified. Time arguments for starttime and endtime are
  the same as the sacct command.

  -----------------
  """
  )

  parser = argparse.ArgumentParser(
    formatter_class=argparse.RawDescriptionHelpFormatter,
    description=desc,
  )
  parser.add_argument("-u", "--user", action="store", dest="user")
  parser.add_argument("-A", "--account", action="store", dest="account")
  parser.add_argument("-S", "--starttime", action="store", dest="starttime")
  parser.add_argument("-E", "--endtime", action="store", dest="endtime")
  args = parser.parse_args(args=None if sys.argv[1:] else ['--help'])

  calc_usage(args.user, args.account, args.starttime, args.endtime)
