#!/usr/bin/python3
# stotal is will calculate the total CPU-hours, GPU-hours, and TRES-hours for a user or account.

import sys,os,subprocess,shlex
import argparse
import time,datetime
from datetime import date

# Calculate Usage
def calc_usage(user, account, starttime, endtime):

  # Get job data
  if user != None:
    jobdata = subprocess.Popen(['sacct','-anPX','--units=G','--format=User,Account,Partition,State,ElapsedRaw,Submit,Start,AllocTRES','-u',user,'-S',starttime,'-E',endtime],
    stdout=subprocess.PIPE,
    universal_newlines=True)
  elif account != None:
    jobdata = subprocess.Popen(['sacct','-anPX','--units=G','--format=User,Account,Partition,State,ElapsedRaw,Submit,Start,AllocTRES','-A',account,'-S',starttime,'-E',endtime],
    stdout=subprocess.PIPE,
    universal_newlines=True)

  for job in jobdata.stdout:
    print(job)
    
# Code starts here.
if __name__ == "__main__":

  desc = (
  """
  stotal
  https://github.com/fasrc/stotal
  ---------------
  stotal is will calculate the total CPU-hours, GPU-hours, and TRES-hours for a Slurm user or account.

  When passed a user or account (note that for accounts outside of what the user is a member of that user must be either an Operator or Administrator), this
  command calculates the total usage for that user or account over the period specified (default is last day). Time arguments for starttime and endtime are
  the same as the sacct command.
    
  -----------------
  """
  )

  parser = argparse.ArgumentParser(
    formatter_class=argparse.RawDescriptionHelpFormatter,
    description=desc,
  )
  parser.add_argument("-u", "--user", action="store", dest="user")
  parser.add_argument("-A", "--account", action="store", dest="account")
  parser.add_argument("-S", "--starttime", action="store", dest="starttime", default="today-1days") 
  parser.add_argument("-E", "--endtime", action="store", dest="endtime", default="today")   
  args = parser.parse_args(args=None if sys.argv[1:] else ['--help'])

  calc_usage(args.user, args.account, args.starttime, args.endtime)